MAKE="Ulyanov, Ulyanovsk"
MODEL="G-807"

GM_TEST_VA="350"
GM_CURRENT_GRID_MIN=-45
GM_CURRENT_PLATE_MA_MAX=200
GM_PLATE_MA_MAX=150
GM_TRANSCONDUCTANCE_MAX=10


RP_TEST_VG="-18"
RP_CURRENT_GRID_MIN=0
RP_VA_MAX=400
RP_CURRENT_PLATE_MA_MAX=75
RP_PLATE_MA_MAX=60
RP_RESISTANCE_KOHM_MAX=60
